source = '''
type = scrapy.Field()
    name = scrapy.Field()
    site = scrapy.Field()
    description = scrapy.Field()
    verify = scrapy.Field()
    link = scrapy.Field()
    expire_at = scrapy.Field()
    coupon_type = scrapy.Field()
    code = scrapy.Field()
    final_website = scrapy.Field()
    store = scrapy.Field()
    store_url_name = scrapy.Field()
    store_description = scrapy.Field()
    store_category = scrapy.Field()
    store_website = scrapy.Field()
    store_country = scrapy.Field()
    store_picture = scrapy.Field()
    created_at = scrapy.Field()
    status = scrapy.Field()
    depth = scrapy.Field()
    download_timeout = scrapy.Field()
    download_slot = scrapy.Field()
    download_latency = scrapy.Field()
'''

source_list = source.replace('    ', '').replace(' = scrapy.Field()', '').split('\n')
for item in source_list:
    print("coupon['%s']=''" % item)
